# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanagement', '0002_auto_20170213_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateuser',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='candidate_cv', verbose_name='CV\xa0File'),
        ),
    ]
