# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 14:41
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Appliance Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=100, verbose_name='Status')),
                ('motivational_text', models.TextField(blank=True, verbose_name='Motivationnal Text')),
            ],
            options={
                'verbose_name': 'Appliance',
                'verbose_name_plural': 'Appliances',
            },
        ),
        migrations.CreateModel(
            name='CandidateUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('file', models.FileField(upload_to='candidate_cv')),
                ('skill', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Candidate User',
                'verbose_name_plural': 'Candidate Users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, upload_to='enterprise_logo', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Enterprise',
                'verbose_name_plural': 'Enterprises',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.Enterprise')),
            ],
            options={
                'verbose_name': 'Enterprise User',
                'verbose_name_plural': 'Enterprise Users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('type', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('interim', 'Interim'), ('freelance', 'Freelance'), ('internship', 'Internship')], max_length=100, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('city', models.CharField(max_length=250, verbose_name='City')),
                ('postcode', models.CharField(max_length=10, verbose_name='Postcode')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], max_length=100, verbose_name='Status')),
                ('skill', models.CharField(blank=True, max_length=100, verbose_name='Skill')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.Enterprise', verbose_name='Enterprise')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.AddField(
            model_name='appliance',
            name='candidate_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.CandidateUser', verbose_name='Candidate User'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.Offer', verbose_name='Offer'),
        ),
    ]
